### ISSUE TITLE
Object cycle detected when running New-Jwt (JSON Serialize issue) 

### ISSUE THREAD

**Issue by UberJoe** [DigitalAXPP/jwtPS#34]
There is some issue with JSON Serialize that happens when i try New-Jwt.
I receive the following error: 
```
Line |
  53 |      $jwt = New-JWT -Payload $payload -Algorithm $alg -Secret $key
     |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than
     | the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support
     | cycles. Path:
     | $.Members.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.OverloadDefinitions.
```

Here's the snippet:
```
$payload = [Ordered]@{
    "iat" = ([System.DateTimeOffset]::Now).ToUnixTimeSeconds()
    "kid" = $islkid
    "hsig" = hashSha256($method + "|" + $webtoken)
    "data" = $data | ConvertTo-Json
}

$encryption = [jwtTypes+encryption]::SHA256
$algorithm = [jwtTypes+algorithm]::RSA
$alg = [jwtTypes+cryptographyType]::new($algorithm, $encryption)

$jwt = New-JWT -Payload $payload -Algorithm $alg -Secret $key
return $jwt
```

I checked the payload in case there was something strange, but it looks OK:
```
[iat, 1673873422] 
[kid, \\default\a] 
[hsig, <hash_value>] 
[data, {}]
```

How can I resolve this error?

**Comment by UberJoe** [comment]
OK, after more investigation the issue seems to occur in the payload when using ConvertTo-Json.

I need to include data as a JSON string in the payload. This was working in the older version

**Comment by UberJoe** [comment]
I fixed it by avoiding using ConvertTo-Json, and instead building the string manually... 
It would be nicer if ConvertTo-Json was supported again for payload parameters.

**Comment by DigitalAXPP** [comment]
Hi @UberJoe ,
Your error reminds me of an error I encountered in the past (https://stackoverflow.com/questions/73276009/the-deserialization-constructor-on-type-fsi-0080-may-not-have-more-than-6).
Does your `data` key have more than 64 entries?
As described in the known issue (https://github.com/dotnet/runtime/issues/71984), this library uses `System.Text.Json.JsonSerializer` for serializing the claimset.
This limitation on the library should be resolved in .NET 8.0-Preview. I don't want to use a preview version however and will update this library once it's available in the next LTS version (.NET 8.0; which should be available in November 2023).

**Comment by UberJoe** [comment]
Hi! 

Thanks for the response.

Actually no, when `data = {}` I still have the error. 
It's something to do with using ConvertTo-Json on `data`. Now I've removed ConvertTo-Json and it works.
